### ISSUE TITLE
TEdiff.R script issue

### ISSUE THREAD

**Issue by vikaskumar1019** [l-modolo/TEtools#1]
Hi Laurent

I am trying to run the TEdiff.R. I am using the command like this:
"Rscript TEdiff.R --args --FDR_level=0.05 --count_column=2 --count_file=Check.count2 --experiment_formula=population:type --sample_names=population1:type1,population1:type2"
The error is:
"[1] "./TEdiff"
Error in eval(expr, envir, enclos) : object 'Check.count2' not found
Calls: eval -> eval
Execution halted"

I guess it is not able to recognise the count_file. I have the count_file "Check.count2" in the same directory where the R script is. If I am using the command in a wrong way. Please let me know what I am doing wrong here.

Thanks

**Comment by l-modolo** [comment]
Hi @vikaskumar1019 , thank you for your interest in TEtools.

This is a problem with the way arguments must be passed to R. I know that the command syntax is not standard but you should keep the double cote and the anti-slash for your text arguments.

Try the following command:

```R
Rscript TEdiff.R --args --FDR_level=0.05 --count_column=2 --count_file=\"Check.count2\" experiment_formula=\"population:type\" --sample_names=\"population1:type1,population1:type2\" --outdir=\"outfolder\" --htmlfile=\"output.html\"
```
