### ISSUE TITLE
TEdiff: main_factor is of length zero

### ISSUE THREAD

**Issue by HeloiseMuller** [l-modolo/TEtools#10]
Hello,

This is my command line:
`Rscript ~/Software/TEtools/TEdiff.R --args --FDR_level=0.05 --count_column=2 --count_file=\"TEcount_Midgut_0hpi_vs_mock\" experiment_formula=\"sample:replicat:condition\" --sample_names=\"Midgut_0hpi_mock:r1:mock,Midgut_0hpi_mock:r2:mock,Midgut_0hpi_mock:r3:mock,Midgut_0hpi:r1:infected,Midgut_0hpi:r2:infected,Midgut_Ohpi:r3:infected\" --outdir=\"RNAseq/TEtools\" --htmlfile=\"TEdiff_Midgut_0hpi.html\"`

I get this error message:
Error in if (main_factor[i] != main_factor[j]) { :  
 argument is of length zero
Execution halted

I looked at TEdiff.R more into details and I saw that the line ` main_factor = levels(variables[,1])` returns NULL. Indeed, variables[,1] is not a factor. I can fix it by replacing it by ` levels(as.factor(variables[,1]))` or by  `unique(variables[,1])` but I do not understand why in my case variables[,1] is not a factor whereas it obviously supposed to be a factor. I am wondering whether I did somtehing wrong or whether it could be a version problem (I have R v4.0) that would not make this variable a factor by default anymore.

To note, I also had a warning message due to the same factor problem:
In DESeqDataSet(se, design = design, ignoreRank) :
 some variables in design formula are characters, converting to factors

Thank you,

Héloïse Muller

**Comment by l-modolo** [comment]
Hello Héloïse,

Indeed I didn’t test this script on R v4.0.*, maybe there was a change in the args parsing packages which now emit vector instead of factors. I think that your fix is good, so you can submit a pull request if you want.

Best,

Laurent Modolo
