### ISSUE TITLE
basic doubt

### ISSUE THREAD

**Issue by adriludwig** [l-modolo/TEtools#12]
Hi,
Really basic question... I didn't get the relationship between the fasta file with the copies and the rosette file.

**Comment by l-modolo** [comment]
Hi @adriludwig,

If you have a fasta file with the following format:

```
>Family_A_copy_1
....
>Family_A_copy_2
....
>Family_A_copy_3
....
>Family_B_copy_1
....
>Family_B_copy_2
....
>Family_B_copy_3
....
```

Then you will need the following rosette file:

```
Family_A_copy_1    Family_A
Family_A_copy_2    Family_A
Family_A_copy_3    Family_A
Family_B_copy_1    Family_B
Family_B_copy_2    Family_B
Family_B_copy_3    Family_B
```

Thus **TEtools** will be able you count all the copies of the TE family A together and all the copies of TE family B together.

Best,

**Comment by adriludwig** [comment]
Thanks very much. I thought that was it, but I wasn't sure
:)
