### ISSUE TITLE
Non reference genome, rosette file format specification?

### ISSUE THREAD

**Issue by rLannes** [l-modolo/TEtools#14]
Hi Laurent, 

I hope you are doing well! Please say hello to Emmanuelle and Christina from me.

I am trying to use TEtools on non-reference genomes. I do have an assembly for my genomes. I ran RepeatMasker and One code to Find Them All.

But then, it is unclear what the rosette file's format is. Is there any format specification?  It seems to be different between what you show on GitHub and what the Melanogaster dataset shows: 

2L|c(20966385..20966456)|DNA/RC|DNAREP1_DM            DNAREP1_DM
2L|(20976274..20976387)|DNA/RC|DNAREP1_DM             DNAREP1_DM

FBti0020418 1360 P DNA
FBti0062753 1360 P DNA

The two files have different numbers of columns. I understand that two columns are mandatory, but should I be worried about the other columns? What are they?

Best regards,
Romain,

**Comment by l-modolo** [comment]
Hi Romain,

You can put any number of columns in your file for your convenience,
The file must be tab separated `\t`

- The first column corresponds to the name of the copy (the same as the one from your genome annotation)
- The second column corresponds to the name of the family the copy correspond to
- The other column are ignored

Best,

**Comment by rLannes** [comment]
Thank you for your quick answer!
Best,
