### ISSUE TITLE
Rossette file

### ISSUE THREAD

**Issue by b12loroc** [l-modolo/TEtools#4]
I don´t understand what do you want to say with rossette file, is an extension? RSD file?, how do i make this file?

**Comment by l-modolo** [comment]
Hi @b12loroc , thank you for your interest in TEtools.
A rosette file is a tabular text format file (.txt, .csv, .tsv, ...). 
You can write it with any text editor or table editor and save the results in that format. The column must be space or tab delimited.

**Comment by b12loroc** [comment]
I download a fasta with trasposon sequences and a csv with their position
in genome, etc.Does reads have to match(fasta and rosette) in order to
build rosette file? would you send me original rosette file in order to
have an example?
Thanks and sorry for this inconvenience
Carmen María López Rodríguez

2018-02-07 14:38 GMT+01:00 Laurent Modolo <notifications@github.com>:

**Comment by e-lerat** [comment]
Here is an example of a rosette file created with the copies from the D. melanogaster genome
[dmel_rosette_new.txt](https://github.com/l-modolo/TEtools/files/1719889/dmel_rosette_new.txt)

As you will see, the rosette file describes each copy using different levels of classification of TEs (family, class etc.)
