### ISSUE TITLE
TEDIFF

### ISSUE THREAD

**Issue by b12loroc** [l-modolo/TEtools#5]
Tecount file is generated without colnames, I send you my file, i have one sample and i wrote: TEdiff.R --args --FDR_level=0.05 --count_column=2 --count_file=\"resultados_H1Rep1.out\" experiment_formula=\"H1Rep1\" --sample_names=\"H1Rep1\" --outdir=\"Resultados_TEDIFF\" --htmlfile=\"Resultados_TEDIFF_FILE\"
I don´t know if this is ok

**Comment by b12loroc** [comment]
[resultados_H1Rep1.txt](https://github.com/l-modolo/TEtools/files/1715971/resultados_H1Rep1.txt)

**Comment by b12loroc** [comment]
What is output extension of output TECOUNT file. I watch this message of TEDIFF Error in dimnames(x) <- dn :
  length of 'dimnames' [1] not equal to array extent
Calls: rownames<-
Execution halted. my rosette file is .txt.

**Comment by l-modolo** [comment]
Hi, @b12loroc 

Your TEcount file seems correct. The last column is the sum of the counts of the line, this means that the 4th column is the counts of the repeat.

Here you only have counts for one sample, so you cannot perform a differential expression analysis with TEdiff. For this you need samples in at least two conditions and more than 3 replicates per condition.

**Comment by b12loroc** [comment]
Thanks for this information!
