### ISSUE TITLE
TECOUNT

### ISSUE THREAD

**Issue by b12loroc** [l-modolo/TEtools#6]
HEllo again!
I run TECOUNT in my cluster, i watch that sam file is building with paired 1. My command is 
TEcount.py -rosette /mnt/home/users/pab_001_uma/b12loroc/dict_pos_ele_tipo_clase_transposon.table.txt -column 2 -TE_fasta /mnt/home/users/pab_001_uma/b12loroc/Hsap38.geve.nt_v1.fa -count resultadosprostata -paciente1_tumor_paired_1_.fastq paciente2_tumor_paired_1_.fastq paciente3_tumor_paired_1_.fastq paciente4_tumor_paired_1_.fastq paciente1_sano_paired_1_.fastq paciente2_sano_paired_1_.fastq paciente3_sano_paired_1_.fastq paciente4_sano_paired_1_.fastq -RNApair paciente1_tumor_paired_2_.fastq paciente2_tumor_paired_2_.fastq paciente3_tumor_paired_2_.fastq paciente4_tumor_paired_2_.fastq paciente1_sano_paired_2_.fastq paciente2_sano_paired_2_.fastq paciente3_sano_paired_2_.fastq paciente4_sano_paired_2_.fastq

**Comment by l-modolo** [comment]
Hi @b12loroc, for paired-end data the TEcount command must bu run as following:

```
TEcount.py -rosette /mnt/home/users/pab_001_uma/b12loroc /dict_pos_ele_tipo_clase_transposon.table.txt \
-column 2 -TE_fasta /mnt/home/users/pab_001_uma/b12loroc/Hsap38.geve.nt_v1.fa \
-count resultadosprostata  \
-RNA paciente1_tumor_paired_1_.fastq paciente2_tumor_paired_1_.fastq paciente3_tumor_paired_1_.fastq paciente4_tumor_paired_1_.fastq paciente1_sano_paired_1_.fastq paciente2_sano_paired_1_.fastq paciente3_sano_paired_1_.fastq paciente4_sano_paired_1_.fastq \
-RNApair paciente1_tumor_paired_2_.fastq paciente2_tumor_paired_2_.fastq paciente3_tumor_paired_2_.fastq paciente4_tumor_paired_2_.fastq paciente1_sano_paired_2_.fastq paciente2_sano_paired_2_.fastq paciente3_sano_paired_2_.fastq paciente4_sano_paired_2_.fastq
```

I think that you forgot the `-RNA` argument

**Comment by b12loroc** [comment]
i have understood that read 1 is after -RNA argument and read 2 is after
-RNApair argument? could you give me an example?
thanks and sorry for this inconvenience
Carmen María Lopez Rodríguez

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2018-02-15 17:50 GMT+01:00 Laurent Modolo <notifications@github.com>:
