### ISSUE TITLE
TEDIFF

### ISSUE THREAD

**Issue by b12loroc** [l-modolo/TEtools#7]
I run TEDIFF and i´m watching this message:
Error: ncol(countData) == nrow(colData) is not TRUE
Execution halted

**Comment by b12loroc** [comment]
Design of DeSeq2  is not functioning correctly? i don´t understand

**Comment by l-modolo** [comment]
Hi @b12loroc , I got your TEcount file.
Could you send me your TEdiff command, so that I can test this bug?

**Comment by b12loroc** [comment]
Hi Laurent, my TEDiff command is: TEdiff.R --args --FDR_level=0.05
--count_column=2 --count_file=\"resultadosmicro\"
experiment_formula=\"sample:replicant:condition\"
--sample_names=\"paciente1_tumor:paciente2_tumor:tumor,paciente1_tumor:paciente3_tumor:tumor,paciente1_tumor:paciente4_tumor:tumor,paciente1_sano:paciente2_sano:sano,paciente1_sano:paciente3_sano:sano,paciente1_sano:paciente4_sano:sano\"
--outdir=\"Resultados_TEDIFF\" --htmlfile=\"Resultados_TEDIFF_FILE\"

**Comment by l-modolo** [comment]
In your case: 
you have 3 column of annotation in your TEcount output. Thus you must use `--count_column=4` as the 4th column of the table is the first one with counts.

You seem to have only 2 factors describing your data: patient#_# and sano vs tumor. Thus you should use something like: `experiment_formula=\"sample:condition\" --sample_names=\"paciente2_tumor:tumor,paciente3_tumor:tumor,paciente1_tumor:tumor,paciente1_sano:sano,paciente1_sano:sano,paciente1_sano:sano\"`

Finally, you have 8 samples in the TEcount output (the last column is the sum of the line). And you describe only 6 samples in the options of TEdiff.

**Comment by b12loroc** [comment]
Thank you again!
sorry for this inconvenience and thank you.
Cheers!
Carmen MAría López Rodríguez

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2018-03-05 11:21 GMT+01:00 Laurent Modolo <notifications@github.com>:
