### ISSUE TITLE
TEcount.py issues

### ISSUE THREAD

**Issue by mb3188** [l-modolo/TEtools#8]
Hello, 
I am trying to run TEcount.py for single end RNAseq reads,  however there is an error I receive that I am not sure what it is refer to (please see below). 
Thanks, 
Martina

Command: :
python3 /data/MB998/HepC_Uwe/TEtools-master/TEcount.py -rosette ROSETA_final -column 2
 -TE_fasta /data/MB998/HepC_Uwe/TEtools-master/All_Repeat_sequences_2.fa -bowtie2 -count Count_result_ALL_ALIGN -RNA Marc_M38_HFLC_DMSOMOCK_D35_24h.fastq.gz Marc_M42_HFLC_DMSOHCV_D35_24h.fastq.gz Marc_M49_HFLC_DMSOMOCK_D73_24h.fastq.gz Marc_M52_HFLC_DMSOHCV_D73_24h.fastq.gz Marc_M62_HFLC_DMSOMOCK_D75_24h.fastq.gz /data/MB998/HepC_Uwe/Marc_M66_HFLC_DMSOHCV_D75_24h.fastq.gz

ERROR LOG: 
counting Marc_M38_HFLC_DMSOMOCK_D35_24h.fastq.gz...
./alignment/Marc_M38_HFLC_DMSOMOCK_D35_24h.fastq.sam
building index
/data/MB998/LUNG_CANCER/TEtools-master/bowtie2/bowtie2-build -f /data/MB998/HepC_Uwe/TEtools-master/All_Repeat_sequences_2.fa /data/MB998/HepC_Uwe/TEtools-master/All_Repeat_sequences_2.fa.index2
Traceback (most recent call last):
  File "/data/MB998/HepC_Uwe/TEtools-master/TEcount.py", line 557, in <module>
    args.insert_size)
  File "/data/MB998/HepC_Uwe/TEtools-master/TEcount.py", line 445, in from_fastq
    self.__mapping_index()
  File "/data/MB998/HepC_Uwe/TEtools-master/TEcount.py", line 395, in __mapping_index
    run_cmd(self.procs, bowtie_cmd)
  File "/data/MB998/HepC_Uwe/TEtools-master/TEcount.py", line 89, in run_cmd
    procs.append(Popen(shlex.split(command), shell=False, stdout=PIPE, stderr=PIPE, bufsize=1))
  File "/home/mb998/lib/python3.7/subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "/home/mb998/lib/python3.7/subprocess.py", line 1499, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)

**Comment by l-modolo** [comment]
Hi @mb3188,

Is `Marc_M66_HFLC_DMSOHCV_D75_24h.fastq.gz` the only fastq.fz file in the `/data/MB998/HepC_Uwe/` folder ?

Otherwise your command should look like:

```
python3 /data/MB998/HepC_Uwe/TEtools-master/TEcount.py -rosette ROSETA_final -column 2
-TE_fasta /data/MB998/HepC_Uwe/TEtools-master/All_Repeat_sequences_2.fa -bowtie2 -count Count_result_ALL_ALIGN -RNA /data/MB998/HepC_Uwe/Marc_M38_HFLC_DMSOMOCK_D35_24h.fastq.gz /data/MB998/HepC_Uwe/Marc_M42_HFLC_DMSOHCV_D35_24h.fastq.gz /data/MB998/HepC_Uwe/Marc_M49_HFLC_DMSOMOCK_D73_24h.fastq.gz /data/MB998/HepC_Uwe/Marc_M52_HFLC_DMSOHCV_D73_24h.fastq.gz /data/MB998/HepC_Uwe/Marc_M62_HFLC_DMSOMOCK_D75_24h.fastq.gz /data/MB998/HepC_Uwe/Marc_M66_HFLC_DMSOHCV_D75_24h.fastq.gz
```
you may have the same problem for the `ROSETA_final` and `All_Repeat_sequences_2.fa` files

**Comment by mb3188** [comment]
Thank you for a fast response. I ran it with a full path to each file (I believe that was suggestion) and still have the same error. 

nohup python3 /data/MB998/HepC_Uwe/TEtools-master/TEcount.py -rosette /data/MB998/HepC_Uwe/TEtools-master/ROSETA_final -column 2 -TE_fasta /data/MB998/HepC_Uwe/TEtools-master/All_Repeat_sequences_2.fa -bowtie2 -count /data/MB998/HepC_Uwe/TEtools-master/Count_result_ALL_ALIGN -RNA /data/MB998/HepC_Uwe/Marc_M38_HFLC_DMSOMOCK_D35_24h.fastq.gz /data/MB998/HepC_Uwe/Marc_M42_HFLC_DMSOHCV_D35_24h.fastq.gz /data/MB998/HepC_Uwe/Marc_M49_HFLC_DMSOMOCK_D73_24h.fastq.gz /data/MB998/HepC_Uwe/Marc_M52_HFLC_DMSOHCV_D73_24h.fastq.gz /data/MB998/HepC_Uwe/Marc_M62_HFLC_DMSOMOCK_D75_24h.fastq.gz /data/MB998/HepC_Uwe/Marc_M66_HFLC_DMSOHCV_D75_24h.fastq.gz &

Traceback (most recent call last):
  File "/data/MB998/HepC_Uwe/TEtools-master/TEcount.py", line 557, in <module>
    args.insert_size)
  File "/data/MB998/HepC_Uwe/TEtools-master/TEcount.py", line 445, in from_fastq
    self.__mapping_index()
  File "/data/MB998/HepC_Uwe/TEtools-master/TEcount.py", line 395, in __mapping_index
    run_cmd(self.procs, bowtie_cmd)
  File "/data/MB998/HepC_Uwe/TEtools-master/TEcount.py", line 89, in run_cmd
    procs.append(Popen(shlex.split(command), shell=False, stdout=PIPE, stderr=PIPE, bufsize=1))
  File "/home/mb998/lib/python3.7/subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "/home/mb998/lib/python3.7/subprocess.py", line 1499, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/data/MB998/LUNG_CANCER/TEtools-master/bowtie2/bowtie2-build'

**Comment by l-modolo** [comment]
Ok,

the line `PermissionError: [Errno 13] Permission denied: '/data/MB998/LUNG_CANCER/TEtools-master/bowtie2/bowtie2-build'` seems to indicate that you don't have execution rights on the tool `bowtie2-build`

You can use the following command to add this right:

`chmod +x /data/MB998/LUNG_CANCER/TEtools-master/bowtie2/bowtie2-build`

You may have to do the same thing for `bowtie2`

**Comment by mb3188** [comment]
That fixed it, thank you so much!
