### ISSUE TITLE
tool update and condafication

### ISSUE THREAD

**Issue by bgruening** [l-modolo/TEtools#9]
Hi @l-modolo!

We got a request to include your tools into https://usegalaxy.eu.
Are you planning to update the tools and maintain them? I have seen that the do not use conda packages and also don't have any tests defined.

Thanks,
Bjoern

**Comment by l-modolo** [comment]
Hi @bgruening ,

Thank you for your interest in TEtools, I am not in the TREEP team anymore, but we plan to do a collaboration to add new features to TEtools.
Maybe we could add test coverage to the code and create a conda package then.

Best,

**Comment by bgruening** [comment]
@l-modolo do you have a timeline for this? I will forward this to our user then :)

Thanks!!

**Comment by lecorguille** [comment]
Hi here,
Is there any progress here? 
Some users would have like to have it on our HPC and we only install tools using Conda or Singularity.

**Comment by lecorguille** [comment]
@l-modolo Can you create a tag `1.0.0` for TEtools, it will help in order to create a Conda package.
Thanks by advance.

**Comment by l-modolo** [comment]
Done, thank you for the packaging effort !

**Comment by lecorguille** [comment]
Thanks for the tag.
Can you give me the correct command to get the `TEdiff.R` version please?
